### ISSUE TITLE
Перегруженный инвентарь грузовиков на базе

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_Operation_first_steps.zargabad#12]
Сложно лутать, т.к. нельзя выбрасывать в ящик.

Лучше разбить на части и занести в:

- Грузовики
- Ящики

При этом разделить по типам -- патроны, оружие, снаряга.

тем более что грузовики могут быть повреждены и хер ты их вывезешь с базы

**Comment by Comrade333** [comment]
добавил ящички

**Comment by 10Dozen** [comment]
ок
