### ISSUE TITLE
Не надо на ГСО вешать все процессы миссии

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_Operation_first_steps.zargabad#15]
https://github.com/rempopo/CO26_Operation_first_steps.zargabad/blob/bf8714681bf43f3e52cc961abf8320e24927fd9c/dzn_tSFramework/Modules/Briefing/tSF_briefing.sqf#L62

Делай скриптами.
Не знаешь как - спрашивай

**Comment by Comrade333** [comment]
переписал

**Comment by 10Dozen** [comment]
ок
