### ISSUE TITLE
Какая вилла! Ничего не стоит, офицер спит на полу, ему ничего не надо, служит за спасибо

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_Operation_first_steps.zargabad#16]
Добавь там мебели какойто, объектов, хули эти голые коридоры штурмовать в 100500900ый раз?

<img src='http://puu.sh/AvUfs/bc68ffdac4.jpg' />

**Comment by Comrade333** [comment]
поигрался в симс

**Comment by 10Dozen** [comment]
ок
