### ISSUE TITLE
Наличие БРДМа это сюрприз о котором никто не знает?

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_Operation_first_steps.zargabad#17]
https://github.com/rempopo/CO26_Operation_first_steps.zargabad/blob/bf8714681bf43f3e52cc961abf8320e24927fd9c/dzn_tSFramework/Modules/Briefing/tSF_briefing.sqf#L21

В брифинге не указано наличие техники, если так и задумывалось (ведь из города никто не заметит стоящий на дороге БРДМ, ага) то ок, но вообще про такое надо упоминать.

Как и про вертолет наемников (хоть его на карте и нет, можно спаунить ВОСЕМЬ ХИНДОВ И ГОНЯТЬ ИГРОКОВ МУХХАХА)

**Comment by Comrade333** [comment]
убрал брдм, на замену пару статик
