### ISSUE TITLE
Нет смысла привязывать ВСЕХ юнитов к одному лоджику dynai/gear

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_Operation_first_steps.zargabad#24]
Вот реально, хоть их там двадцать будет -- это не такая большая нагрузка на систему.

И нет смысла объединять всех "индур" юнитов в одну группу. Кешатся они абсолютно одинаково что внутри одной группы, что в виде нескольких групп. Нахуя вот это дрочить - commandStop (units this);
this forceSpeed 0; - просто безпонятия, время сливать в унитаз, а мог бы брифинг интересный написать.

Аффектят только большое количество патурльных групп и техники - они не кешатся

**Comment by OneScheer** [comment]
Лима меньше надо слушать, это он насоветовал.
