### ISSUE TITLE
Нет описание доступных резервов

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_Operation_first_steps.zargabad#29]
Мы выступаем против армии и нажопников. Очевидно у них есть некие резервы которые могут приехать давать нам пиздюлей или утюжить минометами. Или нет. По брифингу не понятно, что делать ГСО не ясно

**Comment by Comrade333** [comment]
написал про возможные подкрепы

**Comment by 10Dozen** [comment]
ok
