### ISSUE TITLE
ФАРП включон, а где он?

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO26_Operation_first_steps.zargabad#31]
Не отключены не использованные модули

https://github.com/rempopo/CO26_Operation_first_steps.zargabad/blob/bf8714681bf43f3e52cc961abf8320e24927fd9c/dzn_tSFramework/dzn_tSFramework_Init.sqf#L20-L21

https://github.com/rempopo/CO26_Operation_first_steps.zargabad/blob/bf8714681bf43f3e52cc961abf8320e24927fd9c/dzn_tSFramework/dzn_tSFramework_Init.sqf#L23

**Comment by Comrade333** [comment]
выкл

**Comment by 10Dozen** [comment]
ок
